"$schema" = 'https://starship.rs/config-schema.json'

# Which is equivalent to
format = """
$username\
$shlvl\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$docker_context\
$package\
$cmake\
$python\
$ruby\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[hostname]
ssh_only = false

[directory]
truncate_to_repo = false

